### PR TITLE
Allow interface traffic to be used in statistics

### LINKED ISSUE #84: [FEATURE] Introduce utility sensors for packets and bytes on each interface
Pretty simple, introduce day, month, year utility sensors for each interface's packets and bytes sensors

### PR DESCRIPTION
**Pull request by Happyrobot33**
Was lacking the utility sensors I had from when I was using a off the shelf router and integration, so I decided to add them :) I also fixed the fact that the display name of the interface sensors doesn't clean up the _ making them not look good if you directly add them to lovelace without overwriting the display name on a card

closes #84

### CODE REVIEW

**Comment by Happyrobot33** [comment]
Needs fixing, the meters don't seem to reset for some reason. I'm likely reading the documentation wrong

**Comment by Happyrobot33** [comment]
implemented a possible fix, give me a day to see if it works

**Comment by Happyrobot33** [comment]
So I just realized I'm doing this wrong because last_reset is only happening on the sensor creation, not in update. But even reloading the integration doesn't seem to make the value drop to 0, so I really don't know what's wrong

**Comment by Happyrobot33** [comment]
yeah this is more of a pain than I thought it would be, there doesnt seem to be anything a integration can hook into that just does this for them, so itd have to be coded manually to do the difference.....

**Comment by Happyrobot33** [comment]
gonna try to see if I can do it through opnsense's api instead of emulating it in HA

**Comment by Happyrobot33** [comment]
ok so TLDR, im stupid and didnt realize how home assistant statistic sensors worked. all that needed to be changed is for the state_class of some entitys to be total_increasing so home assistant knows how to store them

**Comment by travisghansen** [comment]
Thanks! I know it’s a pain but the `_` business has been discussed ad-nauseam and I’d prefer not mess with that right now :(

The metrics look great! I think we may need to tighten the logic a little bit to ensure it only includes that attribute/value on appropriate sensors. Some of those sensors in that loop may be packets/bytes per second which would not correlate properly to the total increasing property.

**Comment by alexdelprete** [comment]
For cumulative sensors:
- device_class: SensorDeviceClass.DATA_RATE
- state_class: total_increasing

For instant measurement sensors:
- device_class: SensorDeviceClass.DATA_RATE
- state_class: measurement

(reference: https://developers.home-assistant.io/docs/core/entity/sensor)

**Comment by Happyrobot33** [comment]
> Thanks! I know it’s a pain but the `_` business has been discussed ad-nauseam and I’d prefer not mess with that right now :(
> 
> The metrics look great! I think we may need to tighten the logic a little bit to ensure it only includes that attribute/value on appropriate sensors. Some of those sensors in that loop may be packets/bytes per second which would not correlate properly to the total increasing property.

Possibly make the _ configurable then?

**Comment by travisghansen** [comment]
Keeping configuration values at a minimum.

Indeed you are right we should be good for the per second stuff. I'll merge when I get a moment and snap a new release!

**Comment by Happyrobot33** [comment]
> Keeping configuration values at a minimum.
> 
> Indeed you are right we should be good for the per second stuff. I'll merge when I get a moment and snap a new release!

well hold on ill have to remove the `_` change correct?

**Comment by Happyrobot33** [comment]
ive removed the _ change so it should be good to merge @travisghansen

**Comment by travisghansen** [comment]
Thanks for the contribution! This is already available in current releases so closing.

**Pull request closed without merging**
