### PR TITLE
Pyopnsense and coordinator to async

### PR DESCRIPTION
**Pull request by Snuffy2**
### This would probably be good to test as a beta first. No new functionality changes but decent sized behind the scenes changes.

* Moves pyopnsense and coordinator to async to reduce blocking
  * _Can likely optimize the entity classes as well in a future PR_
* Change from `requests` to `aiohttp` for GET and POST calls
  * XMLRPC remains __not__ threadsafe. There are a couple of async/aio versions but I'm not sure how maintained they are. 
* Move coordinator to its own file
* Move `dict_get` to helpers file
* Add more typing hints and annotations
* Standardized case everywhere to be `OPNsense`
* Improved logging and error messages

### CODE REVIEW

**Comment by alexdelprete** [comment]
Sorry for the delay. Looks like a big change, and I agree it's better to release a beta first.

Should we expect big performance improvements?

**Comment by Snuffy2** [comment]
No, likely no real performance improvements. Just bringing the code up to date as HA strongly prefers async code and has started to Warn/Stop code that does any blocking. 

There may be some improvements once I get the entities and services updated but I wouldn't expect much.

**Comment by alexdelprete** [comment]
I upgraded and it seems to be working fine. Let's wait for some more feedbacks.

**Comment by alexdelprete** [comment]
> HA strongly prefers async code and has started to Warn/Stop code that does any blocking.

From what I read, they are enforcing avoiding blocking calls in sync tasks, but sync still makes sense in some cases, the important thing to avoid is blocking calls.

in a couple of integration I made (modbus protocol) I use sync starting a separate task to avoid potential issues.

I have to study your code better, learning a lot from it, I didn't know about aiohttp: I was reading that there's also HTTPX as a requests replacement, that also does automatic json decoding like requests, did you evaluate it?

**Comment by Snuffy2** [comment]
Correct. The best way to avoid blocking is to use async tools when they are available. If not available or not feasible, then spawning these into separate threads/tasks to prevent blocking is necessary. File I/O is the most notable one that doesn't have async tools and XMLRPC in our case.

I use aiohttp as that is what HA uses. aiohttp can also do json decoding if setup that way. I am using an HA method to create an aiohttp session that is setup to do json decoding just like requests. 

https://github.com/travisghansen/hass-opnsense/blob/92fd5be28be51122211e1acd842b99bcec811d7a/custom_components/opnsense/__init__.py#L77

I've not looked at HTTPX as aiohttp has always worked well for me (for HA and non-HA Python projects). It might be great, but I've never looked.

**Comment by alexdelprete** [comment]
> I am using an HA method to create an aiohttp session that is setup to do json decoding just like requests

Yes, so basically you added the missing native functionality. If HA uses aiohttp then your decision makes perfectly sense.

Do you maintain other HA-related projects?

**Comment by Snuffy2** [comment]
Yes, I maintain or co-maintain:
* https://github.com/prestomation/resmed_myair_sensors
* https://github.com/enkama/hass-variables
* https://github.com/custom-components/places
* https://github.com/snicker/juicepassproxy

**Comment by alexdelprete** [comment]
How is the `places` integration different vs the `map` standard integration? I use map to show my tracked devices on the map.

image

**Pull request merged**
