### PR TITLE
ARP table sensor

### PR DESCRIPTION
**Pull request by mdrichardson**
Related: https://github.com/travisghansen/hass-opnsense/discussions/73

This is an attempt to get a sensor listing all of the IPs in the ARP table. 

@travisghansen, I've tried a lot of different variations of `dict_get(state, "arp_table")` and they always return `None`. Via some error logging through `_LOGGER.error(...)`, I can see that the data is retrieved and set successfully [here](https://github.com/travisghansen/hass-opnsense/blob/main/custom_components/opnsense/__init__.py#L309), but if I print out the whole `state` object in my added `native_value()` method, it _never_ has an "arp_table" property. Any idea what's going on?

### CODE REVIEW

**Comment by mdrichardson** [comment]
How's this? Been awhile since I did much in Python, so I'm _real_ open to changing things

**Comment by travisghansen** [comment]
How well is it working in your setup?

There are some improvements to be made to make it more efficient but I can clean those up. I’ll need to rework the coordinator stuff as well.

The subnet logic doesn’t seem valid to me (just reading the code). It looks like you’re taking the first octet and just using that as the subnet?

**Comment by mdrichardson** [comment]
> How well is it working in your setup?
> The subnet logic doesn’t seem valid to me (just reading the code). It looks like you’re taking the first octet and just using that as the subnet?

It's working great!

image
image

I'm totally fine dropping the subnet part. My thought was that it might make it a _little_ easier to build a template sensor for my original use case, but it really wouldn't change it much.

**Comment by travisghansen** [comment]
I see, you were assuming a /24 subnet basically. Regarding the IPs we probably need to structure the data such that it includes the actual mac address etc and not just a list of IPs. Not exactly sure the best way to approach that :(

**Comment by mdrichardson** [comment]
> I see, you were assuming a /24 subnet basically

Yeah. I didn't see a great way to add separate subnets without also adding a bunch of user config options. Maybe the better approach is to have the additional attributes just be a list of tuples containing the ip and mac addresses:

```
clients: [
  (<ip-address1>, <mac-address1>),
  (<ip-address2>, <mac-address2>),
]
```

**Comment by travisghansen** [comment]
Not sure honestly how the data for an arp table is stored. At the end of the day you’re looking for a mac not an ip right? Technically a single mac could have more than 1 ip but I think generally the value of this feature is more focused on macs vs IPs (for examples, for ip there are ping sensors etc that already exist).

**Comment by mdrichardson** [comment]
For my use case, I'm actually only interested in IP addresses. I just need
to be able to see if any devices are connected in my guest IP range.

**Comment by travisghansen** [comment]
I think there was some discussion about getting dhcp stats on a per-interface basis. Is that an easier route?

**Comment by alexdelprete** [comment]
> Technically a single mac could have more than 1 ip

In some cases you can also have a single IP for multiple MACs.

**Comment by travisghansen** [comment]
What scenario would that happen?

**Comment by alexdelprete** [comment]
> What (valid) scenario would that happen?

Devices with multiple cards (wifi + ethernet).

**Comment by travisghansen** [comment]
Each device in such cases has their own mac. I don’t think there’s a valid scenario where a single IP has multiple macs.

**Comment by alexdelprete** [comment]
> Each device in such cases has their own mac. I don’t think there’s a valid scenario where a single IP has multiple macs.

There is: my media players have eth + wifi, and I want my DHCP server to assign the same address whatever interface the device is using.

Same goes for my network printer, it has eth+wifi, and I have the same IP for both interfaces.

**Comment by alexdelprete** [comment]
This is a dnsmasq DHCP config for multiple MACs for 1 reserved IP:

config 'host'
    option 'name' 'printer'
    option 'mac' '99:88:77:66:55:44 ff:ee:dd:cc:bb:aa'
    option 'ip' '192.168.1.104'

**Comment by travisghansen** [comment]
Purposely using arp poisoning is not valid :) Even in failover scenarios (ie: carp) the mac isn’t *shared* but rather is advertised by the active device. The shared screenshot makes my point. You shouldn’t have both wifi and eth enabled simultaneously…and even if you do the arp table of any peer will only respect 1 at any given time.

**Comment by alexdelprete** [comment]
There's no arp poisoning, only 1 interface of the two is active.

**Comment by travisghansen** [comment]
Then we’re back where we started, there’s only 1 mac per IP :)

**Comment by alexdelprete** [comment]
> Then we’re back where we started, there’s only 1 mac per IP :)

Active on the network, yes, not on the DHCP though. :)

**Comment by travisghansen** [comment]
Even then, the lease is ‘abandoned’ so only 1 lease :)

**Comment by alexdelprete** [comment]
> Even then, the lease is ‘abandoned’ so only 1 lease :)

I don't know if at low level the IP is released and re-registered, maybe it's not necessary, the DHCP could simply refresh the ARP table with the new MAC. I didn't sniff it...:)

I added this use-case if maybe there was the idea to scrape DHCP config to get MACs, just be aware that there could be multiple MACs for the same reserved IP.

**Comment by travisghansen** [comment]
As far as the arp table is concerned (on the firewall and any peer) no. As far as dhcp leases no as well.

It is a good point about scraping the config. In practice the dhcp details in the api don’t come from the config but rather the state/leases file.

Each peer may have stale data (ie: arp is pointing to ‘old’ mac address), but peers generally clean this up pretty fast if the arp is no longer valid.

**Comment by alexdelprete** [comment]
ARP tables are refreshed through gratuitous ARP when the interface comes up.

**Comment by alexdelprete** [comment]
@Snuffy2 this PR could be interesting too.

**Pull request closed without merging**
