### PR TITLE
Create HA issue if OPNsense Firmware below min version

### PR DESCRIPTION
**Pull request by Snuffy2**
_screenshot using fake firmware version_

### CODE REVIEW

**Comment by Snuffy2** [comment]
@alexdelprete if you're good with it, I'd say that we merge this PR and then put out v0.2.1
Feel free to put out the release if you have time to.

**Comment by alexdelprete** [comment]
Great. Anything special to write in the notes or can I simply use auto-generation for the release?

**Comment by alexdelprete** [comment]
I was also thinking, now that you added this minimum fw check, if it's possible to check the privileges of the used account and warn the user in case it's not an admin. I don't know if there's an API for that, probably doable via the XMLrpc?

**Comment by Snuffy2** [comment]
I generate an Error if any of the REST queries return a 403 saying there are permission issues.
```python
        elif response.status_code == 403:
            _LOGGER.error(
                f"Permission Error in {inspect.currentframe().f_back.f_code.co_qualname}. Path: {path}. Ensure the OPNsense user connected to HA has full Admin access."
            )
```

I might be able trigger a similar error in the `get_proxy` method to represent XMLRPC permission issues, but I'd need to test more.

**Comment by alexdelprete** [comment]
Sorry, I was referring to the config_flow, in the initial setup phase.

**Pull request merged**
