### PR TITLE
Fix swap memory permission and gracefully handle permission errors

### PR DESCRIPTION
**Pull request by Snuffy2**
* Use different swap memory endpoint that works with current permissions
* Gracefully handle errors, especially permission errors and show this in the Error text
* Add more type hints and annotations

### CODE REVIEW

**Comment by alexdelprete** [comment]
WHile you're preparing this, could you check [this](https://github.com/travisghansen/hass-opnsense/blob/1e354b0802187f10e46d9fbb5aa63fb4ca34fc6a/custom_components/opnsense/pyopnsense/__init__.py#L986) line? the memory variable looks undefined.

**Comment by alexdelprete** [comment]
You went back to `pfstates` vs `pf_states`?

**Comment by Snuffy2** [comment]
> You went back to `pfstates` vs `pf_states`?

Yes, for testing the errors. Not final.

**Comment by alexdelprete** [comment]
Looks good, I'll merge it.

**Pull request merged**
